### ISSUE TITLE
Can use?

### ISSUE THREAD

**Issue by rlpowell** [chuckbjones/todo.txt-cli-addons#2]
I'd like to steal the code to "recur", please, and use bits of it in my rewrite.  I'll be releasing MIT license.  May I?

**Comment by chuckbjones** [comment]
Yes, of course! :thumbsup: I just added the MIT license to the script as well to make it explicit.

**Comment by rlpowell** [comment]
Yay!

**Comment by rlpowell** [comment]
FWIW, here's what I made: https://github.com/rlpowell/todo-text-stuff/blob/master/ice_recur
